name: 'Setup Fonts with Fontist'
description: 'Install fonts using Fontist and Font Awesome'
inputs:
  manifest-path:
    description: 'Path to the fontist manifest file'
    required: false
    default: 'manifest.yml'
  font-awesome-version:
    description: 'Version of Font Awesome to install'
    required: false
    default: '6.7.2'
  ruby-version:
    description: 'Ruby version to use'
    required: false
    default: '3.4'

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Setup Fontist
      shell: bash
      run: |
        gem install fontist
        fontist update

    - name: Install fonts from manifest
      shell: bash
      run: |
        fontist manifest-install -q ${{ inputs.manifest-path }}
        fontist fontconfig update

    - name: Install Font Awesome
      shell: bash
      run: |
        export FA_VERSION=${{ inputs.font-awesome-version }}
        wget https://github.com/FortAwesome/Font-Awesome/releases/download/${FA_VERSION}/fontawesome-free-${FA_VERSION}-desktop.zip
        unzip -q fontawesome-free-${FA_VERSION}-desktop.zip
        mkdir -p ~/.local/share/fonts
        mv fontawesome-free-${FA_VERSION}-desktop/otfs/*.otf ~/.local/share/fonts
