on:
  push:
    branches: [main, dev]
    paths:
      - "lib.typ"
      - "template/*"
      - ".github/workflows/ci.yml"
      - ".pre-commit-config.yaml"
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fontist
        uses: fontist/setup-fontist@v2

      - name: Install fonts
        run: |
          fontist manifest-install manifest.yml
          fontist fontconfig update

      - name: Install Font Awesome
        run: |
          export FA_VERSION=6.7.2
          wget https://github.com/FortAwesome/Font-Awesome/releases/download/${FA_VERSION}/fontawesome-free-${FA_VERSION}-desktop.zip
          unzip fontawesome-free-${FA_VERSION}-desktop.zip
          mkdir -p ~/.local/share/fonts
          mv fontawesome-free-${FA_VERSION}-desktop/otfs/*.otf ~/.local/share/fonts

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Use local package
        run: |
          sed -i 's|#import "@preview/neat-cv:[0-9.]\+"|#import "../lib.typ"|' template/cv.typ

      - name: Compile
        run: just

      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: template/cv.pdf
          retention-days: 7
